/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dinaraparanid_tictactoe_native_libs_ServerNative */

#ifndef _Included_com_dinaraparanid_tictactoe_native_libs_ServerNative
#define _Included_com_dinaraparanid_tictactoe_native_libs_ServerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    readMove
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_readMove
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    runBFSM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_runBFSM
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    sendCorrectMove
 * Signature: ([[B)V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_sendCorrectMove
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    sendInvalidMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_sendInvalidMove
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    sendGameFinished
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_sendGameFinished
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ServerNative
 * Method:    sendRole
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ServerNative_sendRole
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
