/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative */

#ifndef _Included_com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
#define _Included_com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    init
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    sendReady
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_sendReady
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    sendMove
 * Signature: (BB)V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_sendMove
  (JNIEnv *, jobject, jbyte, jbyte);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    readCommand
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_readCommand
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    readRole
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_readRole
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    readTable
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_readTable
  (JNIEnv *, jobject);

/*
 * Class:     com_dinaraparanid_tictactoe_native_libs_ClientPlayerNative
 * Method:    drop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dinaraparanid_tictactoe_native_1libs_ClientPlayerNative_drop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
